import { ArrowRight, CalendarDays, Check, ChevronRight, Heart, Plus, Sparkles, Users, X } from 'lucide-react'
import { friendItems, friends, initialItems } from '../data/mockData'
import type { BorrowRequest, ClosetItem, Identity, Page } from '../types'
import { ItemCard, ItemVisual, PageHeading } from './ClosetUI'

export function Dashboard({ navigate, items, requests, onItem }: { navigate: (page: Page) => void; items: ClosetItem[]; requests: BorrowRequest[]; onItem: (item: ClosetItem) => void }) {
  return <>
    <section className="hero-section"><div className="hero-copy"><p className="eyebrow">Wednesday, June 10</p><h1>Your closet,<br /><em>but social.</em></h1><p>Share what you love. Borrow what you don't own. Get dressed with a little help from your friends.</p><div className="hero-actions"><button className="primary-button" onClick={() => navigate('style')}><Sparkles size={18} /> Style me for Saturday</button><button className="text-button" onClick={() => navigate('friends')}>Browse friends' closets <ArrowRight size={16} /></button></div></div>
      <div className="hero-collage" aria-label="Featured closet items"><div className="collage-card one"><ItemVisual item={friendItems[0]} /><span>Maya's satin dress</span></div><div className="collage-card two"><ItemVisual item={items[0] ?? initialItems[0]} /><span>{items[0]?.name ?? 'Your first upload'}</span></div><div className="scribble">borrow<br />before<br />you buy</div></div></section>
    <section className="stats-row page-container tight"><button onClick={() => navigate('closet')}><strong>{items.length}</strong><span>pieces in your closet</span><ChevronRight /></button><button onClick={() => navigate('closet')}><strong>{items.filter((item) => item.visibility === 'Borrowable').length}</strong><span>ready to borrow</span><ChevronRight /></button><button onClick={() => navigate('requests')}><strong>{requests.filter((request) => request.status === 'Pending').length}</strong><span>open requests</span><ChevronRight /></button></section>
    <section className="page-container dashboard-section"><div className="section-heading inline"><div><p className="eyebrow">Fresh from the group</p><h2>Just shared</h2></div><button className="text-button" onClick={() => navigate('friends')}>See all <ArrowRight size={16} /></button></div><div className="item-grid feature-grid">{friendItems.slice(0, 4).map((item) => <ItemCard key={item.id} item={item} onClick={() => onItem(item)} />)}</div></section>
    <section className="page-container event-banner"><div className="event-date"><span>JUN</span><strong>27</strong></div><div><p className="eyebrow">Upcoming event closet</p><h2>Palm Springs weekend</h2><p>4 friends / 18 shared pieces / 3 outfits waiting</p></div><div className="mini-avatars">{friends.map((friend) => <span key={friend.name} style={{ background: friend.color }}>{friend.initials}</span>)}</div><button className="secondary-button" onClick={() => navigate('event')}>Open event closet <ArrowRight size={16} /></button></section>
  </>
}

export function RequestsPage({ requests, identity, resolveRequest }: { requests: BorrowRequest[]; identity: Identity; resolveRequest: (id: number, status: 'Approved' | 'Declined') => void }) {
  const visible = requests.filter((request) => identity === 'owner' ? request.ownerId === 'owner' : request.requesterId === identity)
  return <section className="page-container"><PageHeading eyebrow="Closet karma" title="Borrow requests" subtitle={identity === 'owner' ? 'Review requests for your shared pieces.' : 'Track everything you asked Brian to borrow.'} />{visible.length ? <div className="requests-layout single"><div><div className="section-heading"><p className="eyebrow">{identity === 'owner' ? 'Needs your answer' : 'Your requests'}</p><h2>{identity === 'owner' ? 'Incoming' : 'Sent to Brian'}</h2></div>{visible.map((request) => <RequestCard key={request.id} request={request} actions={identity === 'owner' && request.status === 'Pending'} resolve={resolveRequest} />)}</div></div> : <div className="empty-state"><Users /><h3>No requests yet</h3><p>{identity === 'owner' ? 'Requests from Alex will appear here.' : "Open a borrowable item in Brian's closet to send one."}</p></div>}</section>
}

function RequestCard({ request, actions, resolve }: { request: BorrowRequest; actions?: boolean; resolve: (id: number, status: 'Approved' | 'Declined') => void }) {
  return <article className="request-card"><div className="request-thumb">{request.glyph}</div><div className="request-copy"><span className={`status ${request.status.toLowerCase()}`}>{request.status}</span><h3>{request.item}</h3><p>{request.requesterName} requested this from {request.person}</p><small><CalendarDays size={14} /> {request.dates}</small>{request.note && <blockquote>“{request.note}”</blockquote>}</div>{actions && <div className="request-actions"><button className="approve" onClick={() => resolve(request.id, 'Approved')}><Check /> Approve</button><button className="decline" onClick={() => resolve(request.id, 'Declined')}><X /> Decline</button></div>}</article>
}

export function StylePage({ visible, generate, onItem, items }: { visible: boolean; generate: () => void; onItem: (item: ClosetItem) => void; items: ClosetItem[] }) {
  const closet = items.length >= 3 ? items : initialItems
  return <section className="style-page"><div className="style-intro page-container"><p className="eyebrow">Your AI stylist + your real-life closet</p><h1>What are we<br /><em>dressing for?</em></h1><p>Tell us the plan. We'll pull from your closet and the pieces your friends are happy to share.</p></div><div className="style-form page-container"><label>Occasion<input defaultValue="Rooftop birthday dinner" /></label><label>Vibe<div className="choice-row"><button className="choice selected">Effortless</button><button className="choice">A little bold</button><button className="choice">Romantic</button></div></label><label>Where?<input defaultValue="Palm Springs / Warm evening" /></label><label className="closet-source">Pull from<div className="choice-row"><button className="choice">My closet only</button><button className="choice selected">Mine + friends'</button></div></label><button className="primary-button generate" onClick={generate}><Sparkles size={19} /> Build my looks</button></div>
    {visible && <div className="outfits page-container"><div className="section-heading"><p className="eyebrow">Built from your saved closet</p><h2>Your looks are ready</h2></div><div className="outfit-grid"><OutfitCard number="01" title="Desert after dark" description="A polished base from your closet with one borrowed statement piece." items={[closet[0], closet[1], friendItems[0]]} onItem={onItem} borrowed="Maya's dress" /><OutfitCard number="02" title="Cool without trying" description="Easy separates from your real saved rack, finished with a friend's accessory." items={[closet[1], closet[2], friendItems[1]]} onItem={onItem} borrowed="Liv's bag" /><OutfitCard number="03" title="Soft power" description="Your closet leads this look, with a borrowed pair of heels for the finish." items={[closet[2], closet[0], friendItems[5]]} onItem={onItem} borrowed="Liv's heels" /></div></div>}
  </section>
}

function OutfitCard({ number, title, description, items, borrowed, onItem }: { number: string; title: string; description: string; items: ClosetItem[]; borrowed: string; onItem: (item: ClosetItem) => void }) {
  return <article className="outfit-card"><span className="outfit-number">LOOK {number}</span><div className="outfit-items">{items.map((item) => <button key={item.id} onClick={() => onItem(item)} aria-label={`View ${item.name}`}><ItemVisual item={item} compact /></button>)}</div><h3>{title}</h3><p>{description}</p><small><Users size={14} /> Borrowing {borrowed}</small><button className="secondary-button"><Heart size={16} /> Save this look</button></article>
}

export function EventPage({ onItem }: { onItem: (item: ClosetItem) => void }) {
  return <section className="page-container"><div className="event-hero"><div><p className="eyebrow">Jun 27 - 29 / Palm Springs, CA</p><h1>Palm Springs<br /><em>weekend</em></h1><p>Pool days, one birthday dinner, and absolutely no panic-shopping.</p></div><div className="sun">PS<br /><span>27</span></div></div><div className="event-members"><div className="mini-avatars large">{friends.map((friend) => <span key={friend.name} style={{ background: friend.color }}>{friend.initials}</span>)}</div><p><strong>You, Maya, Liv, Sam + Nina</strong><br />18 pieces shared for this trip</p><button className="secondary-button"><Plus size={16} /> Invite a friend</button></div><div className="section-heading inline"><div><p className="eyebrow">The shared rack</p><h2>Pack less. Share more.</h2></div><span className="event-note">Everyone can see these</span></div><div className="item-grid">{friendItems.slice(0, 4).map((item) => <ItemCard key={item.id} item={item} onClick={() => onItem(item)} />)}</div></section>
}
